### ISSUE TITLE
Upload Queue - Survey Response detail looks off

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#551]
Below is the current look of the survey response detail on iphone and ipad:
![img_3779 1](https://cloud.githubusercontent.com/assets/1034174/6806993/1957ee8e-d209-11e4-88c8-d701893955d3.PNG)
![img_0297 1](https://cloud.githubusercontent.com/assets/1034174/6807007/22c7f5a4-d209-11e4-8779-acd560947142.PNG)

**Comment by ctrance** [comment]
Team agreed on the current look

**Comment by hongsudt** [comment]
actually, I would like lauren to help style this page.. waiting for @rrocchio @StillSlippery 

but we can close this for now..
