### ISSUE TITLE
support upload through wifi only

### ISSUE THREAD

**Issue by hongsudt** [ucla/ohmageX#655]
Upload wifi only – adding this checkbox option to the native versions, because students using limited phone data is a concern. This requires adding: exception(s) to the upload process, configuration option to the user profile, and likely a build config option for setting that checkbox to default Yes or No depending on deployment

added info: just learned from some teachers that many of their students ended up using the browser-survey taking tool to collect data since they didn't want to waste any of their data plan on school work!

**Comment by ctrance** [comment]
working good now!
