### ISSUE TITLE
After survey submit, request the submitted survey response using survey response read for merging into response history

### ISSUE THREAD

**Issue by wrenr** [ucla/ohmageX#715]

**Comment by ctrance** [comment]
Please do the same thing on dashboard too, upon successful survey upload update the dashboard counters.

**Comment by wrenr** [comment]
Auto-update was not a requested feature with history. It only updates when the user activates the refresh button. However, when this issue's described functionality is implemented to merge the uploaded single response with the current response history, the response count will automatically update itself

**Comment by StillSlippery** [comment]
Shouldn't this automatically happen after a submit?  The object that puts the counts into the dashboard view should be aware of the additional data that's in the local store, correct?

**Comment by wrenr** [comment]
dashboard view data is generated from response history, it is not linked to anything else

**Comment by ctrance** [comment]
@wrenr - History and dashboard now auto-refresh after uploading survey from the Survey page but it doesn't auto-refresh if I upload from Upload Queue.

**Comment by ctrance** [comment]
Refreshing now after uploading from the queue
