### ISSUE TITLE
History - deleted response still shows even after refreshing the page

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#718]
I deleted a response on the server then tap refresh icon on the history page but the deleted response still show on the app

**Comment by wrenr** [comment]
Delete response functionality has not been implemented. The button is there but the action has not been created.

**Comment by ctrance** [comment]
@wrenr - I didn't delete it from the app, I deleted the response from the frontend then I refresh the history list

**Comment by ctrance** [comment]
fixed
