### ISSUE TITLE
Fix dashboard ui 

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#721]
Please fix the dashboard issues below:
- The icons are tiny
- Missing open survey icons for Initial and Concluding 
![screenshot_2015-07-30-17-40-35 1](https://cloud.githubusercontent.com/assets/1034174/9113858/9c7bb414-3c0b-11e5-9e4e-ee00086a46d5.png)

**Comment by wrenr** [comment]
Dashboard UI was not fully implemented for that build, only functionality. A verified design comp would also be required for formal approval on the final UI for this feature

**Comment by ctrance** [comment]
Fixed
