### ISSUE TITLE
Remove 'dashboard' in ohmageX

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#730]
Generic ohmageX should not have 'dashboard', please remove.
![img_6629](https://cloud.githubusercontent.com/assets/1034174/9210287/3b38e48c-4030-11e5-8216-9f15c13b49d5.PNG)

**Comment by wrenr** [comment]
not intended to be included, typo in build config

**Comment by ctrance** [comment]
@wrenr - I just installed the latest ohmageX-dev but I still see 'dashboard' on the menu

**Comment by ctrance** [comment]
latest ohmageX build doesn't have dashboard anymore

**Comment by ctrance** [comment]
OhmageX doesn't show dashboard anymore
