### ISSUE TITLE
Remove history and dashboard on Mobilize version

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#731]
For the mobilizingcs version, please remove both history and dashboard.

**Comment by wrenr** [comment]
not intended to be included, typo in build config

**Comment by stevenolen** [comment]
@wrenr can you point out the typo? should it be "dashboardeqis" instead of "dashboard_eqis"? I can modify the mobilize config, but just want to confirm before I do so.

**Comment by wrenr** [comment]
I already pushed a fix for it


________________________________

**Comment by stevenolen** [comment]
didn't really look like it
https://github.com/ucla/ohmageX/blob/develop/appconfig/mobilize.json#L50

suggests "dashboard_eqis" but when I set this to "dashboardeqis" the menu *actually* goes away, as in #739

**Comment by wrenr** [comment]
pushed removing history from build config as well


________________________________

**Comment by ctrance** [comment]
I don't see history and dashboard on mobilize build anymore. Closing this
