### ISSUE TITLE
Group and Survey filters on nexus 9 tablet show blank list

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#732]
On nexus 9 tablet os 5.0.2, the history filters show blank, see screenshots below:
![screenshot_2015-08-12-07-16-36 1](https://cloud.githubusercontent.com/assets/1034174/9226596/3e373f6e-40c4-11e5-9960-8dd3cf0aadcb.png)
![screenshot_2015-08-12-07-17-34 1](https://cloud.githubusercontent.com/assets/1034174/9226600/458c1dc0-40c4-11e5-9c12-fedc57cf2edf.png)

**Comment by wrenr** [comment]
Are other dropdowns in the app doing this? There is no rendering difference between these dropdowns and other dropdowns in the app.

**Comment by ctrance** [comment]
@wrenr - Yes, same thing happens on the reminder's survey dropdown. It only happens on nexus 9 tablet which the e-Qis project will use.

**Comment by wrenr** [comment]
Confirmed at the meeting 2015-08-13 that this does not happen on the e-QIS tablets, only on the testing tablet

**Comment by ctrance** [comment]
I just upgraded the nexus 9 tablet os to 5.1.1 but the dropdown list still shows blank very weird error

**Comment by ctrance** [comment]
The dropdown issue got fixed after updating the android os to the latest and deleting>re-installing eqis app.
