### ISSUE TITLE
Back button doesn't work on nexus 9 tablet

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#741]
The back button on nexus 9 tablet doesn't work on eqis

**Comment by wrenr** [comment]
Does the back button work after the recent back button fixes?

**Comment by hongsudt** [comment]
yay!  The back button seems to work on my phone now..  Will need @ctrance
to test on nexus 9...

Thanks Wren..

**Comment by ctrance** [comment]
The back button is working good on Nexus 9 tablet now.
