### ISSUE TITLE
Label changes

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#746]
As mentioned in our meeting today please do the following text changes:
1.History
 -change filters to "Days" and "Artifacts"
2.Artifacts 
 -change the network upload error message to "The artifact cannot be uploaded due to some network error. Retry or click OK to save the artifact in the upload queue."
3.Dashboard
-If no installed portfolio show "No installed portfolios. Please install a portfolio by going to Menu > Portfolio then tap the download icon."
4.Reminders
-If no installed portfolio show "No installed portfolios. Please install a portfolio by going to Menu > Portfolio then tap the download icon."
-If no reminders show "No reminders. Please tap + to add a new reminder"

**Comment by wrenr** [comment]
As mentioned in the meeting, the filter that contains Day 1, Day 2 ... Day 10 also contains the names of the other surveys. Because this filter contains the Initial and Concluding Assessments, its contents include other labels that are not "Days". The "Days" label is not accurately descriptive of its contents and is thus currently labeled "Groups" because of this potential confusion. If desired, any alternative solutions are welcome.

**Comment by ctrance** [comment]
@wrenr - It was decided from today's meeting to change the history filters to say "Folders" (instead of show groups) and "Artifacts" (instead of show artifacts"

**Comment by ctrance** [comment]
@wrenr - Please only do the label changes below, as mentioned from yesterday's meeting:

1. History filters:  Show Groups --> Folders and Show Artifacts --> Artifacts
2. Dashboard message when no installed portfolios: "No installed portfolios. Tap the menu bars on the top left corner and click Portfolio. Then click on the download icon."
3. No network error message:	Network error; the artifact cannot be uploaded. Retry or click OK to save the artifact to the upload queue."
4. Artifact notifications:	* Assessment Artifacts: Tap to capture. Swipe to ignore.
* Instruction Artifacts: Tap to capture. Swipe to ignore.
5. History details delete confirmation message: Are you sure you want to delete this artifact? (Yes or No)


The two bugs we found today --- 	
Reminder - delete option 	We do not get a warning/confirmation message when I delete a reminder
Reminder - Notification bug 	We are not getting a notification when we schedule a repeated reminder

I selected repeat and M T W and did not get a notificationfor the scheduled time

**Comment by ctrance** [comment]
@wrenr - Pending label changes:
4. Artifact notifications: * Assessment Artifacts: "Tap to capture. Swipe to ignore." - current app version shows "Take survey Assessment Artifacts".
6. History details delete confirmation message: Are you sure you want to delete this artifact? (Yes or No) - current app shows ok and cancel buttons except yes and no.

**Comment by ctrance** [comment]
They also want to change this message "Validation Error: This page contains an invalid response. Please resolve before continuing." to "Incomplete Data Error: Please answer all questions""

**Comment by wrenr** [comment]
This is a non-trivial task, there is currently no special case for "all responses were not answered" and there is no case for distinguishing an empty response vs a response that contains a different error.

________________________________

**Comment by ctrance** [comment]
@wrenr - how about the other label changes?
4. Artifact notifications: "Tap to capture. Swipe to ignore." instead of "Take survey Assessment Artifacts".
6. History details delete confirmation message: Are you sure you want to delete this artifact? (Yes or No) - current app shows ok and cancel buttons except yes and no.

**Comment by hongsudt** [comment]
What about ...

Validation Error: This page is either incomplete or contains an invalid
response. Please resolve before continuing.

**Comment by hongsudt** [comment]
To summarize all the label changes: 
* Validation Error: This page is either incomplete or contains invalid responses. Please resolve before continuing.
* Artifact reminder notifications: "Tap to capture. Swipe to ignore." 
* History details delete confirmation message: Are you sure you want to delete this artifact? Select OK to proceed.

**Comment by ctrance** [comment]
@wrenr - reminder message is too long "Tap to capture Assessment Artifacts artifact. Swipe...". it should only be "Tap to capture. Swipe to ignore." 

Everything else looks good

**Comment by ctrance** [comment]
Will retest this once I got new build for eQis

**Comment by stevenolen** [comment]
@ctrance not sure if you saw, but newer builds should be available for eqis/android

**Comment by ctrance** [comment]
fixed
