### ISSUE TITLE
Device's back button stops working after survey submission

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#753]
If I haven't submitted a survey response the device's back button works but after submitting one it no longer works. I tested this on mobilize and e-qis build, nexus 5 phone os 5.1.1

**Comment by hongsudt** [comment]
@wrenr This happens only on the multi-prompt display mode.

**Comment by wrenr** [comment]
Forced disable of upload tracker on survey exit and survey reset. Added non-device debugging for back button functionality for faster testing, worked

**Comment by ctrance** [comment]
@wrenr - I just downloaded the latest e-qis but the back button doesn't work even before submitting a survey response. 

I went to Portfolio > installed eqis v4 > selected the portfolio > taken to the dashboard but tapping the device's back button didn't work.

**Comment by wrenr** [comment]
Added a VERY quick fix attempt, let me know if this works with the latest latest build

**Comment by hongsudt** [comment]
@ctrance just tested.. The back still still doesn't work after submission..

**Comment by ctrance** [comment]
Back button is working good on e-Qis now
