### ISSUE TITLE
Skipped prompt didn't show in the Upload Queue

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#761]
If the prompt is skipped, it doesn't appear in the Upload Queue details page.

**Comment by ctrance** [comment]
Still not fixed on the latest version

**Comment by ctrance** [comment]
Upload Queue detail page shows skipped prompt as "unsupported", see below
![capture](https://cloud.githubusercontent.com/assets/1034174/9962906/1ef603ca-5ddd-11e5-81cb-9aa42711e09f.jpg)

**Comment by wrenr** [comment]
Working on all test devices here. Any past items added to the upload queue in a previous version of the app will not work, they do not contain the necessary metadata. When testing this feature, one must create new items to test in the upload queue after installing the newest version.

<img width="314" alt="screen shot 2015-09-18 at 10 42 26 am" src="https://cloud.githubusercontent.com/assets/865444/9966516/32a39ab2-5df2-11e5-8c92-61bb4d561a67.png">

**Comment by wrenr** [comment]
It looks like all responses have been affected, not just skipped responses. They work on refresh.  looking into this

**Comment by hongsudt** [comment]
Can we also shorten the text just to have an italic

*skipped? *
Thanks

**Comment by ctrance** [comment]
Skip prompt is now showing
