### ISSUE TITLE
Tapping Upload Queue in the menu doesn't redirect to upload queue list

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#762]
If I'm in the upload queue details page (opened one of the pending uploads) and I tap Upload Queue from the menu, the app doesn't take me back to the main list. I used to be redirected back to main list if I tap the Upload Queue from the details page.

**Comment by wrenr** [comment]
fixed now that upload queue uses a full screen modal, menu is no longer accessible until the modal is closed

**Comment by hongsudt** [comment]
Neat!

@ctrace can you check whether issue #3 and #4 from yesterday is fixed due
to this change?  If so, maybe we can offer this build as an option.

**Comment by ctrance** [comment]
Menu is no longer available when viewing the upload queue details. Tapping X takes the user back to the list and using the device back button works as well. Closing this
