### ISSUE TITLE
Can't move forward after choosing to upload another image

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#764]
I just revised e-Qis Portfolio 5 to make image upload a series of questions (up to 5) but after uploading the first image and selected Yes to upload another image the app won't go forward. There's no error showing. Please use "Instruction Artifact" survey
![screenshot_2015-09-04-07-05-47 1](https://cloud.githubusercontent.com/assets/1034174/9501294/509c24c8-4bdf-11e5-826f-c09e062d0df3.png)

**Comment by ctrance** [comment]
Below is the xml for the series of uploading questions:

<prompt>
          <id>1stInstructionImage</id>
          <displayLabel>1stInstructionImage</displayLabel>
          <promptText>Please upload the image.</promptText>
          <promptType>photo</promptType>
          <condition>(3InstructionMaterialType == 0)</condition>
          <skippable>false</skippable>
          <properties>
            <property>
              <key>res</key>
              <label>720</label>
            </property>
          </properties>
        </prompt>
        <prompt>
          <id>2ndInstructionImageOption</id>
          <displayLabel>2ndInstructionImageOption</displayLabel>
          <promptText>Would you like to upload another image?</promptText>
          <condition>(3InstructionMaterialType == 0)</condition>
          <promptType>single_choice</promptType>
          <skippable>false</skippable>
          <properties>
            <property>
              <key>0</key>
              <label>Yes</label>
            </property>
            <property>
              <key>1</key>
              <label>No</label>
            </property>            
          </properties>
        </prompt>
        <prompt>
          <id>2ndInstructionImage</id>
          <displayLabel>2ndInstructionImage</displayLabel>
          <promptText>Please upload the second image.</promptText>
          <promptType>photo</promptType>
          <condition>(2ndInstructionImageOption == 0) and (3InstructionMaterialType == 0)</condition>
          <skippable>false</skippable>
          <properties>
            <property>
              <key>res</key>
              <label>720</label>
            </property>
          </properties>
        </prompt>
        <prompt>
          <id>3rdInstructionImageOption</id>
          <displayLabel>3rdInstructionImageOption</displayLabel>
          <promptText>Would you like to upload another image?</promptText>          
          <promptType>single_choice</promptType>
          <condition>(2ndInstructionImageOption == 0) and (3InstructionMaterialType == 0)</condition>
          <skippable>false</skippable>
          <properties>
            <property>
              <key>0</key>
              <label>Yes</label>
            </property>
            <property>
              <key>1</key>
              <label>No</label>
            </property>
          </properties>
        </prompt>
        <prompt>
          <id>3rdInstructionImage</id>
          <displayLabel>3rdInstructionImage</displayLabel>
          <promptText>Please upload the third image.</promptText>
          <promptType>photo</promptType>
          <condition>(3rdInstructionImageOption == 0) and (3InstructionMaterialType == 0)</condition>
          <skippable>false</skippable>
          <properties>
            <property>
              <key>res</key>
              <label>720</label>
            </property>
          </properties>
        </prompt>
        <prompt>
          <id>4thInstructionImageOption</id>
          <displayLabel>4thInstructionImageOption</displayLabel>
          <promptText>Would you like to upload another image?</promptText>
          <promptType>single_choice</promptType>
          <condition>(3rdInstructionImageOption == 0) and (3InstructionMaterialType == 0)</condition>
          <skippable>false</skippable>
          <properties>
            <property>
              <key>0</key>
              <label>Yes</label>
            </property>
            <property>
              <key>1</key>
              <label>No</label>
            </property>
          </properties>
        </prompt>
        <prompt>
          <id>4thInstructionImage</id>
          <displayLabel>4thInstructionImage</displayLabel>
          <promptText>Please upload the fourth image.</promptText>
          <promptType>photo</promptType>
          <condition>(4thInstructionImageOption == 0) and (3InstructionMaterialType == 0)</condition>
          <skippable>false</skippable>
          <properties>
            <property>
              <key>res</key>
              <label>720</label>
            </property>
          </properties>
        </prompt>
        <prompt>
          <id>5thInstructionImageOption</id>
          <displayLabel>5thInstructionImageOption</displayLabel>
          <promptText>Would you like to upload another image?</promptText>
          <promptType>single_choice</promptType>
          <condition>(4thInstructionImageOption == 0) and (3InstructionMaterialType == 0)</condition>
          <skippable>false</skippable>
          <properties>
            <property>
              <key>0</key>
              <label>Yes</label>
            </property>
            <property>
              <key>1</key>
              <label>No</label>
            </property>
          </properties>
        </prompt>
        <prompt>
          <id>5thInstructionImage</id>
          <displayLabel>5thInstructionImage</displayLabel>
          <promptText>Please upload the fifth image.</promptText>
          <promptType>photo</promptType>
          <condition>(5thInstructionImageOption == 0) and (3InstructionMaterialType == 0)</condition>
          <skippable>false</skippable>
          <properties>
            <property>
              <key>res</key>
              <label>720</label>
            </property>
          </properties>
        </prompt>

**Comment by wrenr** [comment]
I figured out the problem.

The survey multi flow checks for an invalid future reference in the condition by evaluating the stepID.

The following IDs exist in this survey:

    2ndInstructionImage
    2ndInstructionImageOption

If a condition contains a reference to `2ndInstructionImageOption`, the parser checks for BOTH `2ndInstructionImage` and `2ndInstructionImageOption`! There is no way to distinguish the two.

**Comment by ctrance** [comment]
@wrenr and @hongsudt - From the previous meeting the flow they wanted was after uploading a photo ask the user if it wants to upload again (max of 5). Is this not possible in the current state? Should we just show all 5 photo prompt and make them skippable?

**Comment by hongsudt** [comment]
I am not sure I understand the limitation that wren mentioned..  Maybe we
can discuss this over the meeting in case there is a workaround.

In the meantime, it might be wise to have a backup plan.. So create a
another campaign that you suggested. I don't think Filipe is going to like
this last minute change though (especially it is not what he wanted)..

**Comment by wrenr** [comment]
I'm already fixing it

**Comment by wrenr** [comment]
no need to create a new campaign ,fix pushed

**Comment by ctrance** [comment]
Awesome I'll retest once there's new eqis build!

**Comment by ctrance** [comment]
fixed
