### ISSUE TITLE
VA -Stuck in a survey if there's a conditional message

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#765]
I just uploaded the new VA survey with conditional message and repeating skipped prompts. But I can’t move forward to the conditional message. I’m basically stuck on the prompt prior to the conditional message, tapping Next or Skip doesn’t take me anywhere.

Please use the new VA Pain Study campaign, connecting to pilots.mobilizelabs.

**Comment by ctrance** [comment]
Below are the conditions for the message prompt:
'<message>
          <id>EndOfSurveyMessage</id>
          <condition>
            (Eligibility == SKIPPED) or (OptInOut == SKIPPED) or (AnswerRefusalQuestions == SKIPPED) or (ReasonNotParticipating == SKIPPED) or (IsVeteranInPain == SKIPPED) or (VetsEstimatedAge == SKIPPED) or (VetsGender == SKIPPED)
            or (VetsRace == SKIPPED) or (AveragePainLastWeek == SKIPPED) or (PainLifeEnjoymentInterferance == SKIPPED) or (PainGeneralActivityInterferance == SKIPPED) or (NRSOneWeek == SKIPPED) or (NRSNow == SKIPPED) or (HavingSignificantPainToday == SKIPPED)
            or (PainRightNow == SKIPPED) or (PainAverageOverLastMonth == SKIPPED) or (WorstPainOverLastMonth == SKIPPED) or (DaysInPainLastMonth == SKIPPED) or (DaysPainInterferedWithUsualActivities == SKIPPED)
            or (PainInterferedWithDailyActivities == SKIPPED) or (PainInterferedWithRecreationalSocialFamilyActivities == SKIPPED) or (PainInterferedWithWorkActivities == SKIPPED) or (PeaceFeeling == SKIPPED) or (ActiveComparisonToOthers == SKIPPED)
            or (ManageYourPainUsingOtherWayEffectivity == SKIPPED) or (ImportanceOfPainDiscussionWithDoctor == SKIPPED)
          </condition>
          <messageText>
            Thank you! Please give this device back to the RA if you are done or tap back to change any answers.
          </messageText>
        </message>'

**Comment by wrenr** [comment]
At the previous meeting @hongsudt mentioned there may be an issue with the parentheses grouping, did changing this grouping resolve this?

**Comment by hongsudt** [comment]
@ctrance is on vacation.. I don't think she has done any more testing since
last Friday...

**Comment by ctrance** [comment]
@hongsudt and @wrenr Grouping the conditions still didn't work
`<condition>
            ((Eligibility == SKIPPED) or (OptInOut == SKIPPED) or (AnswerRefusalQuestions == SKIPPED) or (ReasonNotParticipating == SKIPPED)) 
            or ((IsVeteranInPain == SKIPPED) or (VetsEstimatedAge == SKIPPED) or (VetsGender == SKIPPED)or (VetsRace == SKIPPED))
            or ((AveragePainLastWeek == SKIPPED) or (PainLifeEnjoymentInterferance == SKIPPED) or (PainGeneralActivityInterferance == SKIPPED) or (NRSOneWeek == SKIPPED))
            or ((NRSNow == SKIPPED) or (HavingSignificantPainToday == SKIPPED) or (PainRightNow == SKIPPED) or (PainAverageOverLastMonth == SKIPPED))
            or ((WorstPainOverLastMonth == SKIPPED) or (DaysInPainLastMonth == SKIPPED) or (DaysPainInterferedWithUsualActivities == SKIPPED) or (PainInterferedWithDailyActivities == SKIPPED))
            or ((PainInterferedWithRecreationalSocialFamilyActivities == SKIPPED) or (PainInterferedWithWorkActivities == SKIPPED) or (PeaceFeeling == SKIPPED) or (ActiveComparisonToOthers == SKIPPED))
            or ((ManageYourPainUsingOtherWayEffectivity == SKIPPED) or (ImportanceOfPainDiscussionWithDoctor == SKIPPED))
          </condition>`

**Comment by hongsudt** [comment]
@ctrance you still have more than 4 clauses at the top level. Put more
parenthesis to make sure you don't have more than that eg ( ( () or () ...
) or ( () or () or ... ) )

**Comment by ctrance** [comment]
@hongsudt - I made the top level 4 max clauses but the app still get stuck.
`<message>
          <id>EndOfSurveyMessage</id>
          <condition>
            (((Eligibility == SKIPPED) or (OptInOut == SKIPPED) or (AnswerRefusalQuestions == SKIPPED) or (ReasonNotParticipating == SKIPPED)) or ((WorstPainOverLastMonth == SKIPPED) or (DaysInPainLastMonth == SKIPPED) or (ManageYourPainUsingOtherWayEffectivity == SKIPPED)))
            or (((IsVeteranInPain == SKIPPED) or (VetsEstimatedAge == SKIPPED) or (VetsGender == SKIPPED)or (VetsRace == SKIPPED)) or ((DaysPainInterferedWithUsualActivities == SKIPPED) or (PainInterferedWithDailyActivities == SKIPPED)))
            or (((AveragePainLastWeek == SKIPPED) or (PainLifeEnjoymentInterferance == SKIPPED) or (PainGeneralActivityInterferance == SKIPPED) or (NRSOneWeek == SKIPPED)) or ((PainInterferedWithRecreationalSocialFamilyActivities == SKIPPED) or (PainInterferedWithWorkActivities == SKIPPED)))
            or (((NRSNow == SKIPPED) or (HavingSignificantPainToday == SKIPPED) or (PainRightNow == SKIPPED) or (PainAverageOverLastMonth == SKIPPED)) or ((PeaceFeeling == SKIPPED) or (ActiveComparisonToOthers == SKIPPED) or (ImportanceOfPainDiscussionWithDoctor == SKIPPED)))            
          </condition>
          <messageText>
            Thank you! Please give this device back to the RA if you are done or tap back to change any answers.
          </messageText>
        </message>`

**Comment by ctrance** [comment]
@wrenr - Breaking the long condition into multiple conditional messages has worked! Closing this.
