### ISSUE TITLE
build regression: blockfile no longer exists a exec:block_build step

### ISSUE THREAD

**Issue by stevenolen** [ucla/ohmageX#770]
@wrenr, it looks like 52e0fd06408998331fa0fddaa3c147821b3ec579 creates a build regression when builds are done as suggested in README.md.  The Blockfile.rb file in time for `grunt exec:blocks_builds`. Please re-document how you'd like builds to proceed. jenkins builds are blocked (heh, blocks) on this. Below are the steps per the README.md for clean workspace execution.

```bash
bundle
npm install
export NODE_PATH=$(npm config get prefix)/lib/node_modules
node_modules/grunt-cli/bin/grunt exec:blocks_build
node_modules/grunt-cli/bin/grunt dev
```

**Comment by wrenr** [comment]
Execute `grunt template:blockfile` before trying to build web blocks and it should work

**Comment by wrenr** [comment]
Actually, I went ahead and replaced the reference to grunt exec:blocks_build with a new task, grunt webblocks_build that generates the template dependency beforehand. The README has also been updated with this new reference.

**Comment by ctrance** [comment]
@stevenolen and @wrenr - I don't think I need to test this right?

**Comment by stevenolen** [comment]
haha nope, we're good now. i've "tested" the fix and it's working :+1:
