### ISSUE TITLE
suppress the notification in the case of successfully putting a response in the upload queue

### ISSUE THREAD

**Issue by hongsudt** [ucla/ohmageX#771]
When there is a network error, the app asks for a retry or save to upload queue. If the response is saved successfully, please don't show a successful message. This is to minimize the number of clicks to exit the survey.

**Comment by wrenr** [comment]
This was requested behavior to notify the user that an item was placed in the upload queue when exiting the survey. Abandon the requested behavior?

**Comment by hongsudt** [comment]
Yes.. Can you comment out the code? I would like to try the flow without
it..

After clicking the submit button, if it is offline, the message say..
"Network Error - Retry or select OK to save the survey to the upload
queue."
If I click ok, it said "Your response has been added to the Upload Queue".

I think the network error message is pretty clear already.  This will
minimize the # of clicks to exit the survey from 3 to 2.  Since we add the
wifi-upload only option, there will be more chances for them to go through
this flow.

Can you please capitalize the word upload queue in the network error
message e.g. "Network Error - Retry or select OK to save the survey to the
Upload Queue."?

Thanks

**Comment by hongsudt** [comment]
Also, because of the newly added feature of having # of outstanding
responses next to the upload queue menu, this should easily catch the
users' eyes..

**Comment by ctrance** [comment]
@wrenr - I still get the message "Your response has been added to the Upload Queue" after selecting "Ok" on the network error.

**Comment by wrenr** [comment]
I have not made any changes to this feature, will move to Test when ready for testing

**Comment by ctrance** [comment]
Both android and ios version already suppresses the saving to the upload queue on upload error.
