### ISSUE TITLE
Disable next button if user is at the last record

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#782]
On the history details page, please disable the "next" button if user is at the last record and disable "previous" button if user is at the first record.

**Comment by wrenr** [comment]
If at the end and going forward, it goes back to the beginning, and if at the beginning and going backwards, it rotates back to the end. This is common app behavior

**Comment by ctrance** [comment]
@wrenr - they don't like the rotating behavior, and wanted disabling the button instead.

**Comment by wrenr** [comment]
Let's discuss this request at the next e-QIS meeting.

**Comment by ctrance** [comment]
Put item counter instead
