### ISSUE TITLE
Changes on Survey Exit page

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#783]
On the exit page please change the following:
1. Change "Artifact submitted." message to "Artifact added to the Upload Queue" if the responses didn't submit to the server.
2. Change "Exit" button to "Done"
![screenshot_2015-10-02-11-34-32 1](https://cloud.githubusercontent.com/assets/1034174/10254724/6061d1ae-68fa-11e5-89a4-8ee172898324.png)

**Comment by wrenr** [comment]
The new Thank You text is "Artifact uploaded or added to the Upload Queue."

**Comment by ctrance** [comment]
Button has changed to "Done" now. I'll change the campaign xml for the new message.

**Comment by ctrance** [comment]
@wrenr - Per @stevenolen "The text will need to be made configurable per deployment in ohmageX, or that page removed if the manage reminders feature is disabled!"

I'm reopening this since I can't change it from the campaign xml.

**Comment by ctrance** [comment]
The decided upload message from the meeting was “Artifact successfully uploaded or stored on the queue”.

**Comment by ctrance** [comment]
fixed
