### ISSUE TITLE
Dashboard not updating after artifact successful upload

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#794]
Looks like the Day folders on the dashboard are not updating after successful upload. I just successfully uploaded Assessment and Instruction artifacts for Day 1 folder. The server shows the artifacts but on the app the counter on the dashboard still show "0"

**Comment by ctrance** [comment]
Client requested to rename the folders with A. Initial Reflection, Day 01-10, and Z. Concluding Reflection to sort correctly on the History page.

**Comment by ctrance** [comment]
@wrenr - The dashboard now updates folders Day 01-10 except reflection and concluding (A. Initial Reflection and Z. Concluding Reflection).

**Comment by wrenr** [comment]
If the names of the initial and concluding surveys changes, this breaks. They have to be hard coded for dashboard bucketing. Will these change again?

**Comment by ctrance** [comment]
I don't think they'll change those again, they just wanted to add A. and Z. so the app will sort according to their needs.

**Comment by ctrance** [comment]
fixed
