### ISSUE TITLE
Video/Doc file doesn't open after downloading manually from the History page

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#796]
I just uploaded an instruction artifact with video attachment then went to History. My connection speed was 15.46 mbps and the video size is 51mb. I tapped the view button and the downloading spinner shows immediately with 0% throughout the download - no progress at all. Then the spinner went away and nothing happened (video didn't open - app shows no error message)

**Comment by ctrance** [comment]
Same thing happens when downloading/opening document from History. This time the download progress shows 24% but didn't progress. The spinner goes away then nothing happened...

**Comment by ctrance** [comment]
@wrenr - I still get this issue at home with 23.33 mbps wifi connection. Online viewing used to work (before the spinner got added), maybe it's my current os too which 6.0 now...

**Comment by wrenr** [comment]
no changes were made to the file opener plugin. The previous comment indicates a new issue, because a major OS update could cause the existing file opener plugin to break.

If the download is failing during the download progress that's just displaying an error message.

**Comment by ctrance** [comment]
Will test this once I get new build for eQis

**Comment by ctrance** [comment]
@wrenr Video still not opening (online) after the download spinner went away...nothing happens I didn't even get the opening progress.

**Comment by wrenr** [comment]
Cannot reproduce, able to open all videos without issues

**Comment by wrenr** [comment]
Clear the File Cache by activating the Clear File Cache button in the Profile page then re-download the video file. Does it work?

**Comment by wrenr** [comment]
Do you have a 5.x device to test this on?

**Comment by ctrance** [comment]
All devices I have are updated to 6.0

**Comment by ctrance** [comment]
I cleared cache from the Profile page and viewing the document (*.xls) worked the video still doesn't open though after downloading (progress % doesn't changed tho it just goes away)

**Comment by ctrance** [comment]
Online (.pdf doc and video) Spinner progress doesn't increase after few seconds it will go away then nothing happens...

**Comment by ctrance** [comment]
Doc is opening now. The video still doesn't open, spinner shows no progress > disappears > nothing happens...

**Comment by ctrance** [comment]
@wrenr - If the doc didn't auto-download and user tries to download it manually from the History page, the spinner shows non-increasing progress disappears then show "unable to open.." message. Same case with videos

**Comment by wrenr** [comment]
yes, in that case there is a problem with reading the file and it's not going to be able to be downloaded in any circumstance.

**Comment by ctrance** [comment]
Video is opening now
