### ISSUE TITLE
Document not auto-downloaded after artifact uploading

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#798]
I just uploaded an artifact with a document which successfully submitted to the server. I went offline then went to History, the app shows error "file does not exist on the device..."

**Comment by wrenr** [comment]
Did you go offline before hitting "Done"? The survey is not done until the Done button is pressed or the user exits.

**Comment by ctrance** [comment]
I tapped Done button to exit the survey after successful uploading then I went offline

**Comment by wrenr** [comment]
was this the latest build? Cannot reproduce if so.

**Comment by ctrance** [comment]
@wrenr - I was testing the build today before 12:22. I'll install the latest build which was 3 mins ago and retest. Did you update your OS to 6.0 as well?

**Comment by wrenr** [comment]
No, I'm using the same 5.1 OS as the deployment

**Comment by wrenr** [comment]
Do you have a 5.x device to test this on?

**Comment by ctrance** [comment]
@wrenr - I only have 6.0 device to test this on, both tablet and phone got updated to the latest OS

**Comment by ctrance** [comment]
I still get "file not on the device" error when viewing offline after successful uploading to the server.

**Comment by ctrance** [comment]
online: app is opening the doc but throws error "file format not supported". I opened the same .docx file using the native 'docs' app on the phone and it opened successfully.
offline: I get 'file does not exist on the device..." error.

**Comment by StillSlippery** [comment]
I get similar errors offline if I’m trying to open a file that I don’t have an app on the device that can read it.

**Comment by StillSlippery** [comment]
I only get this error if I’m trying to view a file (offline) that I get the error “cannot display longuuid.pdf is of invalid file type” while online.

**Comment by ctrance** [comment]
When I view the.xls doc online, I got 'allow google sheets to open the file' message. After allowing it docx, pdf, xls are opening now. I also get to view the docx after uploading successfully then going offline.

**Comment by ctrance** [comment]
I was also able to open the document after logging out and logging back in.

**Comment by ctrance** [comment]
downloaded and can be opened now
