### ISSUE TITLE
docx gets 'file format is not supported' 

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#799]
I'm online and viewing the artifact with docx attachment that I just uploaded successfully to the server, but the app shows error "file format is not supported"

**Comment by ctrance** [comment]
I used to view docx before...

**Comment by wrenr** [comment]
I've made no changes to how docx is handled, that's the File Opener plugin.

**Comment by wrenr** [comment]
Do you have a 5.x device to test this on?

**Comment by ctrance** [comment]
@wrenr the docx file was from Google drive which I've been using before that used to open but not opening now and showing file format not supported

**Comment by ctrance** [comment]
I'll create new docx and see if it will throw same error

**Comment by ctrance** [comment]
same thing...

**Comment by ctrance** [comment]
i can view it now
