### ISSUE TITLE
android versioncode not unique enough

### ISSUE THREAD

**Issue by stevenolen** [ucla/ohmageX#800]
The android version code currently gets generated as a non-decimal format of the `version` field found in `config.xml` (ie for 3.0.3 it's `30003`).  If you try to upload two different 3.0.3 builds to the store though, the store will reject because the version code is not higher than the last uploaded.

With the native app in the past, we've actually used one generated based on the day: `15102101` where the code reads `YYMMDDxx` and xx is incremented as needed to ensure the ability to upload multiple apps from the same build day.  It would nice to follow a similar structure (and just use `01` always) to facilitate easier store deploys.  

You can modify this field in the cordova `config.xml` file in the top level `<widget>` tag by specifying as: `android-versionCode="15102101"`

**Comment by wrenr** [comment]
how many digits can be in the android version code?

**Comment by wrenr** [comment]
if I don't get a response, I'm going to use a Unix epoch with most of the end digits truncated.

**Comment by stevenolen** [comment]
Cap it at the length I suggested earlier, 8.

It needs to be incremented up though, so timestamp might be awkward.

I don't know the limit but I'm sure it's easy enough to look up..not at a
computer at the moment..

**Comment by wrenr** [comment]
Timestamp truncated to 8 increments every 2 minutes, we should be good

**Comment by stevenolen** [comment]
I had suggested using the date as mentioned since mobilize is already using
it, and its something that I will still have to customize now on mobilize
release until after we pass 15 in the first two digits of the UNIX
timestamp.

**Comment by stevenolen** [comment]
http://developer.android.com/tools/publishing/versioning.html#appversioning

The docs just say "...set to any integer you want". Perhaps we could just set it 10 digits instead, that way all future version codes will be higher than any existing apps deployed to the store.

**Comment by wrenr** [comment]
so I'll prepend 15 to the unix timestamp then?

**Comment by StillSlippery** [comment]
Yeah, just ten digits increasing is probably the best bet. Just like DNS serial numbers.

Sent from my iPhone

On Oct 21, 2015, at 1:16 PM, Steve Nolen <notifications@github.com<mailto:notifications@github.com>> wrote:


http://developer.android.com/tools/publishing/versioning.html#appversioning

The docs just say "...set to any integer you want". Perhaps we could just set it 10 digits instead, that way all future version codes will be higher than any existing apps deployed to the store.

-

**Comment by stevenolen** [comment]
oh, no just use first 10 digits of the timestamp is fine (since even 1400000000 is bigger than 15100101, which is the curren versioncode for the mobilize version.

**Comment by stevenolen** [comment]
(and 10 happens to actually just be a unix timestamp length...)

**Comment by stevenolen** [comment]
working now!
