### ISSUE TITLE
Biggest doc didn't auto-download after uploading to the server

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#802]
Not all docs are auto-downloaded after uploading to the server, then went offline. I attached 3 docs to 1 artifact (docx-354.9kb, xls-23.6, pdf-10kb) the biggest file which is the docx show error “file does not exist on the device…”

**Comment by wrenr** [comment]
Did it show "1 of 3 images or documents failed to download" pop up? Or did it appear that it was successful?

**Comment by ctrance** [comment]
I got that download failure pop up later when uploading brand new artifact, so at first I didn't know it was for that one of the docs. Did it fail because of the file size? Maybe we should show auto-download spinner while the app is downloading images/docs then show that download failure message.

**Comment by wrenr** [comment]
Are you using the latest build? The new build should block the entire UI and say "Fetching file 1 of 30..." "fetching file 2 of 30..." until all files have downloaded.

**Comment by ctrance** [comment]
I used the one with timestamp 12:22pm today

**Comment by wrenr** [comment]
yeah there's a new build with lots of fixes for file download

**Comment by ctrance** [comment]
Okay I see there's a 1:37pm build, I'll try that

**Comment by ctrance** [comment]
A 354kb docx file failed to auto-download but the 11.1kb docx is successful. It looks like it's failing because of the size. If I try to download that 354kb docx manually from History I get "unable to open" but the smaller docx file opens...

**Comment by ctrance** [comment]
fixed
