### ISSUE TITLE
App generated multiple simultaneous reminders after rebooting the phone

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#823]
@wrenr I have a repeating reminder to trigger on Monday/Wednesday/Friday at 5 pm. The Wednesday, Friday, and Monday triggered without issue on the device. But after I rebooted the phone (both latest OS 7.1.1 and previous OS 6.0.1), the app generated 3 simultaneous reminders, see screenshot below:
![screenshot_20170224-170101](https://cloud.githubusercontent.com/assets/1034174/22937001/116101b6-f28c-11e6-8d1b-5e98e910ad19.png)

**Comment by wrenr** [comment]
Confirmed reproduced in a bare bones Cordova app on Android 5.1., using the Local Notifications plugin `every` parameter to create 3 separate weekly reminders for Wednesday, Thursday, and Friday. It happens even if those existing notifications have been cleared from the notification center before restarting.

**Comment by wrenr** [comment]
@ctrance I tried advancing the clock 1 week and repeating the process... the notifications repeated again. However -

this appears to only happen in a specific circumstance on Android 5.1. The device time when I rebooted was Friday at 5pm.

If, before rebooting, I advance the clock into the future, to a different time that doesn't match a notification trigger time, it does NOT trigger the duplicating notifications. Can you please test and verify? In my example I moved my clock to Sunday at 8:07pm.
![device-2017-02-21-155618](https://cloud.githubusercontent.com/assets/865444/23190688/5032d37a-f84e-11e6-95ba-a5a7824b5d5f.png)

**Comment by ctrance** [comment]
@wrenr - I still get the bug even if I set the dateTime to future not matching any notification. I logged out of the app before testing again. I set a multiple reminder to trigger on MWF at 7 am. I triggered the W and F 7 am reminders without rebooting the phone. Before rebooting the phone I set the dateTime to Saturday 7:01 am, then reboot. I set the dateTime to Sunday 7:03 am, then set the dateTime again to M 6:03 am. At 7 am, the app generated 3 simultaneous reminders (screenshot below):

Tested on Nexus 5 OS 6.0.1
![screenshot_20170227-070029](https://cloud.githubusercontent.com/assets/1034174/23216568/46e9a21c-f8cb-11e6-925d-e0b975350da0.png)

**Comment by ctrance** [comment]
The app re-trigger reminders that already went off after rebooting the device.

**Comment by wrenr** [comment]
The following procedure DOES NOT created the error on an Android 7, bare bones Cordova app that creates 3 total weekly notifications on Wed, Thu, and Fri after startup:

- set time/date to Tuesday 1pm
- set time/date to wed 5pm - wait for notif to go off
- set time/date to thu 5pm - wait for notif to go off
- set time/date to fri 5pm - wait for notif to go off
- clear the notifications from notification center
- set time/date to saturday at 7pm
- turn it off
- wait a couple of minutes before turning it back on
- wait a couple of minutes before unlocking the phone to check

I even set the time the following Wed at 5pm, and it showed the single reminder, as before.

**Comment by ctrance** [comment]
@wrenr - The multiple reminder issue did not happen if I follow the steps above.

**Comment by ctrance** [comment]
This issue does not happen also if I change the dateTime to a non-matching reminder schedule before and after rebooting the phone. Then when I change the dateTime again to a matching reminder schedule, the app only generates 1 reminder. I'm closing this.
